### ISSUE TITLE
Provide extra variable for the route53_zone data source

### ISSUE THREAD

**Issue by ldormoy** [cloudposse/terraform-aws-acm-request-certificate#11]
### Problem
I want to create this certificate:
```
domain_name                  = "site.example.org"
subject_alternative_names = ["www.site.example.org"]
```

My existing Route53 hosted zone is `example.org.`

The module fails because it looks for the `site.example.org` zone, which does not exist. I want to keep my `example.org` zone and I don't want to create a wildcard certificate.

### Solution
* add extra variable `zone_name`
* use variable `zone_name` as name for the route53_zone data source if it exists:
```hcl
variable "zone_name" {
  type        = "string"
  default     = ""
  description = "The Hosted Zone name of the desired Hosted Zone"
}

data "aws_route53_zone" "default" {
  count        = "${var.process_domain_validation_options == "true" && var.validation_method == "DNS" ? 1 : 0}"
  name         = "${local.zone_name}"
  private_zone = false
}

locals {
  zone_name = "${var.zone_name == "" ? var.domain_name. : var.zone_name}"
}
```

I am happy to write a PR if you agree with the proposed solution.

**Comment by aknysh** [comment]
@ldormoy  thanks, that should work.
Please open a PR
