### ISSUE TITLE
`aws_route53_record.default` errror

### ISSUE THREAD

**Issue by albttx** [cloudposse/terraform-aws-acm-request-certificate#16]
```
Error: module.acm_request_certificate.aws_route53_record.default: 1 error(s) occurred:

* module.acm_request_certificate.aws_route53_record.default: At column 3, line 1: lookup: argument 1 should be type map, got type string in:

${lookup("null_resource.default.${count.index}", "resource_record_type")}
```

Sorry i just copy pasting my error because i'm a beginner with terraform, 

(i'm using the configuration on the readme (with my domain name)

**Comment by purefn** [comment]
I'm seeing the same error. I'm guessing it's because we're using a newer version of terraform and this module hasn't been updated to support the newer aws provider.
