### ISSUE TITLE
external DNS validation (e.g. Cloudflare)

### ISSUE THREAD

**Issue by babebort** [cloudposse/terraform-aws-acm-request-certificate#64]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature
It would be great if the module could be used with external DNS validation (e.g. Cloudflare).
This is already implemented in [https://registry.terraform.io/modules/terraform-aws-modules/acm/aws/latest](similar module)

**Comment by nitrocode** [comment]
This is only for aws provider. If youd like it for cloudflare, then i think a new repo would be needed
