### ISSUE TITLE
Add ability to specify key_algorithm for certs setup with this module

### ISSUE THREAD

**Issue by acorncom** [cloudposse/terraform-aws-acm-request-certificate#69]
### Describe the Feature

As described in this blog post (https://aws.amazon.com/blogs/security/how-to-evaluate-and-use-ecdsa-certificates-in-aws-certificate-manager/), it is now possible to issue ECDSA certs using ACM. And the underlying Terraform module (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate) supports the `key_algorithm` option that lets us set that. However this module doesn't currently allow passing that value in

### Expected Behavior

I'd expect to be able to pass `key_algorithm=EC_prime256v1` and see the appropriate cert generated in ACM

### Use Case

ECDSA certs use less bandwidth and computation power to work. They're starting to be used more heavily in IoT deploys as described in the above blog post

### Describe Ideal Solution

We'd add a new option to this module

**Comment by gw0** [comment]
I would expect this too.
